version: '3.7'

services:
  postgres:
    container_name: postgres_keycloak
    image: bitnami/postgresql:latest
    environment:
      - TZ=America/Guayaquil
      - POSTGRESQL_TIMEZONE=America/Guayaquil
      - POSTGRESQL_LOG_TIMEZONE=America/Guayaquil
      - POSTGRESQL_PASSWORD=my-password
      - POSTGRESQL_POSTGRES_PASSWORD=paswodwde
    volumes:
      - postgres_data:/bitnami/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRESQL_USERNAME']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure:5

  keycloak_sp:
    container_name: keycloak_sp
    image: quay.io/keycloak/keycloak:latest
    command: 'start-dev'
    environment:
      - KC_DB=postgres
      - KC_HEALTH_ENABLED=true
      - KC_DB_URL=jdbc:postgresql://postgres:5432/postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=my-password
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
      - ROOT_LOGLEVEL=DEBUG
    volumes:
      - ./email-to-username-mapper-1.0.jar:/opt/keycloak/providers/email-to-username-mapper-1.0.jar
    ports:
      - 9080:8080
    depends_on:
      postgres:
        condition: service_healthy
  idp:
    image: kenchan0130/simplesamlphp
    container_name: idp
    ports:
      - 8080:8080
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: http://localhost:9080/realms/sp_realm
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:9080/realms/sp_realm/broker/saml/endpoint
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: http://localhost:9080/realms/sp_realm/broker/saml/endpoint
    volumes:
      - ./authsources.php:/var/www/simplesamlphp/config/authsources.php
volumes:
  postgres_data:
  ldap_data:
  ldap_config:
